#!/usr/bin/env python3
"""
Generic Linux prompt/hotkey board runtime.

The runtime consumes build/linux_hotkey_board/board_spec.json. It is not tied to
any particular product name except through the compiled spec generated by tools/compile_hotkey_board_linux.py.
"""

from __future__ import annotations

import argparse
import configparser
import html
import json
import os
import platform
import shutil
import signal
import subprocess
import threading
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, urlparse
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

try:
    from terminal_copy_providers import copy_terminal_buffer_with_provider
except ModuleNotFoundError:
    import importlib.util as _importlib_util

    _provider_path = Path(__file__).resolve().parent / "terminal_copy_providers.py"
    _provider_spec = _importlib_util.spec_from_file_location(
        "terminal_copy_providers",
        _provider_path,
    )
    if _provider_spec is None or _provider_spec.loader is None:
        raise

    _provider_module = _importlib_util.module_from_spec(_provider_spec)
    sys.modules.setdefault("terminal_copy_providers", _provider_module)
    _provider_spec.loader.exec_module(_provider_module)
    copy_terminal_buffer_with_provider = _provider_module.copy_terminal_buffer_with_provider

DEFAULT_SPEC = "build/linux_hotkey_board/board_spec.json"
DEFAULT_SETTINGS = {
    "enable_global_chat_hotkeys": "1",
    "enable_numpad_mode": "0",
    "remember_numpad_mode": "0",
}

PROMPT_COACH_TEXT = """You are helping me create a strong reusable AI prompt.

I am still learning how to write prompts, so do not assume I know the best structure yet. Interview me briefly, one question at a time, until you understand what I am trying to accomplish.

For each question:
1. Ask the question.
2. Explain why it matters.
3. Give a recommended answer if there is an obvious best practice.
4. Explain what changes based on my answer.

Help me decide whether this should be:
- a current-session instruction,
- a new-session prompt,
- a reusable workflow prompt,
- a troubleshooting prompt,
- a design prompt,
- an implementation prompt,
- a research prompt,
- or a prompt for another specific task.

Before producing the final prompt, check for:
- missing context,
- unclear task boundaries,
- output format requirements,
- tone/style requirements,
- tools or files the AI should or should not use,
- constraints,
- failure risks,
- whether the prompt should assume existing chat context or be self-contained.

When ready, produce:
1. The finished prompt.
2. A short explanation of how to use it.
3. A warning about any assumptions or weak points.

Important:
If the current chat has a lot of unrelated context, tell me to start a new chat and paste the final prompt there.
Do not overcomplicate the result. Make the final prompt clear, practical, and ready to paste."""

FORGE_TRANSFORMATIONS = [
    "Merge / Combine",
    "Repair",
    "Compress",
    "Expand",
    "Specialize",
    "Convert to Implementation Prompt",
    "Convert to Design-Doc Prompt",
    "Convert to AI-CAD Prompt",
    "Convert to Academic/Writing Prompt",
    "Convert to Current-Session Instruction",
    "Convert to New-Session Prompt",
]


class Clipboard(Protocol):
    def copy(self, text: str) -> None: ...
    def paste(self) -> str: ...


class MemoryClipboard:
    def __init__(self) -> None:
        self.value = ""

    def copy(self, text: str) -> None:
        self.value = text

    def paste(self) -> str:
        return self.value


class ExternalClipboard:
    def __init__(self) -> None:
        self.copy_command = self._detect_copy_command()
        self.paste_command = self._detect_paste_command()

    @staticmethod
    def _detect_copy_command() -> list[str] | None:
        if shutil.which("wl-copy"):
            return ["wl-copy"]
        if shutil.which("xclip"):
            return ["xclip", "-selection", "clipboard"]
        if shutil.which("xsel"):
            return ["xsel", "--clipboard", "--input"]
        return None

    @staticmethod
    def _detect_paste_command() -> list[str] | None:
        if shutil.which("wl-paste"):
            return ["wl-paste", "--no-newline"]
        if shutil.which("xclip"):
            return ["xclip", "-selection", "clipboard", "-out"]
        if shutil.which("xsel"):
            return ["xsel", "--clipboard", "--output"]
        return None

    def copy(self, text: str) -> None:
        if not self.copy_command:
            raise RuntimeError("No clipboard command found. Install wl-clipboard, xclip, or xsel, or use Tk clipboard from the GUI.")
        subprocess.run(self.copy_command, input=text.encode("utf-8"), check=True)

    def paste(self) -> str:
        if not self.paste_command:
            return ""
        proc = subprocess.run(self.paste_command, check=False, capture_output=True)
        if proc.returncode != 0:
            return ""
        return proc.stdout.decode("utf-8", errors="replace")


class TkClipboard:
    def __init__(self, root: Any) -> None:
        self.root = root

    def copy(self, text: str) -> None:
        self.root.clipboard_clear()
        self.root.clipboard_append(text)
        self.root.update_idletasks()

    def paste(self) -> str:
        try:
            return str(self.root.clipboard_get())
        except Exception:  # noqa: BLE001 - Tk raises TclError without clipboard data.
            return ""

# Terminal copy quality policy:
# - "full" is transcript-backed and safe for default/auto proof.
# - "partial_visible_only" is allowed only when the provider explicitly
#   returns success, for the current Konsole/live fallback path.
TERMINAL_COPY_ACCEPTED_QUALITIES = {"full", "partial_visible_only"}


def copy_terminal_text_to_system_clipboard(text: str, fallback_clipboard: Clipboard) -> str:
    """Copy Copy-Terminal-Buffer text to the real desktop clipboard.

    Native GUI toolkits can keep their own clipboard state under some Wayland/X11
    combinations. Copy Terminal Buffer is a system-facing action, so full
    transcript text is written through the external clipboard backend first.
    MemoryClipboard remains the test backend and still receives terminal text in
    unit tests.
    """
    if isinstance(fallback_clipboard, MemoryClipboard):
        fallback_clipboard.copy(text)
        return "memory"

    errors: list[str] = []
    try:
        external = ExternalClipboard()
        if external.copy_command:
            external.copy(text)
            return "external:" + " ".join(external.copy_command)
        errors.append("external clipboard command unavailable")
    except Exception as exc:  # noqa: BLE001 - fallback may still work.
        errors.append(f"external clipboard failed: {exc}")

    try:
        fallback_clipboard.copy(text)
        return type(fallback_clipboard).__name__
    except Exception as exc:  # noqa: BLE001 - report all attempted clipboard paths.
        errors.append(f"fallback clipboard failed: {exc}")
        raise RuntimeError("Could not write terminal buffer to clipboard. " + "; ".join(errors)) from exc


@dataclass(frozen=True)
class PromptRecord:
    section: str
    profile_id: str
    board_id: str
    slot: int
    label: str
    path: str


class BoardSpec:
    def __init__(self, repo_root: Path, spec_path: Path, data: dict[str, Any]) -> None:
        self.repo_root = repo_root
        self.spec_path = spec_path
        self.data = data
        self.product_name = data.get("product", {}).get("name", "Hotkey Board")
        self.folder_name = data.get("product", {}).get("folder_name", repo_root.name)
        model = data.get("model", {})
        self.profiles: list[dict[str, str]] = list(model.get("profiles", []))
        self.boards: list[dict[str, str]] = list(model.get("boards", []))
        self.prompts_per_board = int(model.get("prompts_per_board", 0) or 0)
        self.settings_rel = data.get("source", {}).get("settings_path", "config/settings.ini")
        self.prompts: list[PromptRecord] = [
            PromptRecord(
                section=item["section"],
                profile_id=item["profile_id"],
                board_id=item["board_id"],
                slot=int(item["slot"]),
                label=item["label"],
                path=item["path"],
            )
            for item in data.get("prompts", [])
        ]
        self._prompt_by_key = {(p.profile_id, p.board_id, p.slot): p for p in self.prompts}

    @classmethod
    def load(cls, repo_root: Path, spec_rel_or_abs: str) -> "BoardSpec":
        spec_path = Path(spec_rel_or_abs)
        if not spec_path.is_absolute():
            spec_path = repo_root / spec_path
        data = json.loads(spec_path.read_text(encoding="utf-8"))
        schema = data.get("schema_version")
        if schema != "linux-hotkey-board-spec-v1":
            raise ValueError(f"Unsupported board spec schema: {schema}")
        return cls(repo_root=repo_root, spec_path=spec_path, data=data)

    def prompt(self, profile_index: int, board_index: int, slot: int) -> PromptRecord:
        profile = self.profiles[profile_index]
        board = self.boards[board_index]
        key = (profile["id"], board["id"], slot)
        if key not in self._prompt_by_key:
            raise KeyError(f"No prompt for {profile['id']}.{board['id']}.{slot:02d}")
        return self._prompt_by_key[key]

    def prompt_body(self, prompt: PromptRecord) -> str:
        prompt_path = self.repo_root / prompt.path
        body = prompt_path.read_text(encoding="utf-8")
        if not body.strip():
            raise ValueError(f"Prompt file is empty: {prompt.path}")
        return body

    def validate_prompt_files(self) -> list[str]:
        errors: list[str] = []
        for prompt in self.prompts:
            path = self.repo_root / prompt.path
            if not path.is_file():
                errors.append(f"Missing prompt Markdown file: {prompt.path}")
                continue
            if not path.read_text(encoding="utf-8").strip():
                errors.append(f"Empty prompt Markdown file: {prompt.path}")
        return errors


class SettingsStore:
    def __init__(self, path: Path, initial: dict[str, str] | None = None) -> None:
        self.path = path
        self.values = dict(DEFAULT_SETTINGS)
        if initial:
            self.values.update({key: str(value) for key, value in initial.items() if key in DEFAULT_SETTINGS})
        self.load()

    def load(self) -> None:
        if not self.path.exists():
            return
        cp = configparser.ConfigParser()
        cp.read(self.path, encoding="utf-8")
        if not cp.has_section("settings"):
            return
        for key in DEFAULT_SETTINGS:
            value = cp["settings"].get(key, self.values[key]).strip().lower()
            self.values[key] = "1" if value in {"1", "true", "yes", "on"} else "0"

    def save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        cp = configparser.ConfigParser()
        cp["settings"] = self.values
        with self.path.open("w", encoding="utf-8") as handle:
            cp.write(handle)

    def enabled(self, key: str) -> bool:
        return self.values.get(key, "0") == "1"

    def set_enabled(self, key: str, enabled: bool, *, persist: bool = True) -> None:
        self.values[key] = "1" if enabled else "0"
        if persist:
            self.save()


def collect_diagnostics(spec: BoardSpec | None = None) -> dict[str, Any]:
    session_type = os.environ.get("XDG_SESSION_TYPE", "unknown") or "unknown"
    has_display = bool(os.environ.get("DISPLAY"))
    has_wayland = bool(os.environ.get("WAYLAND_DISPLAY"))
    pynput_available = False
    keyboard_available = False
    pynput_error = ""
    keyboard_error = ""
    tk_available, tk_error = tkinter_available()
    pyqt_available, pyqt_error = pyqt6_available()
    pygobject_ok, pygobject_error = pygobject_available()
    native_gui_backend = "tk" if tk_available else "qt" if pyqt_available else "gtk_available_not_used_yet" if pygobject_ok else "web"
    try:
        import pynput.keyboard  # type: ignore  # noqa: F401

        pynput_available = True
    except Exception as exc:  # noqa: BLE001
        pynput_error = str(exc)
    try:
        import keyboard  # type: ignore  # noqa: F401

        keyboard_available = True
    except Exception as exc:  # noqa: BLE001
        keyboard_error = str(exc)

    if session_type.lower() == "wayland":
        global_hotkey_status = "unavailable_or_desktop_portal_required"
        global_hotkeys_available = False
        reason = "Wayland sessions normally block arbitrary global key capture/injection for regular apps."
    elif session_type.lower() == "x11" and (pynput_available or keyboard_available):
        global_hotkey_status = "possibly_available_experimental"
        global_hotkeys_available = True
        reason = "X11 plus a Python hotkey backend was detected, but live registration still requires testing on this desktop."
    elif session_type.lower() == "x11":
        global_hotkey_status = "backend_missing"
        global_hotkeys_available = False
        reason = "X11 was detected, but no supported Python global hotkey backend imported successfully."
    else:
        global_hotkey_status = "unknown_session"
        global_hotkeys_available = False
        reason = "The runtime could not identify a supported global hotkey setup."

    return {
        "platform": platform.platform(),
        "python": sys.version.split()[0],
        "session_type": session_type,
        "display": os.environ.get("DISPLAY", ""),
        "wayland_display": os.environ.get("WAYLAND_DISPLAY", ""),
        "has_display": has_display,
        "has_wayland_display": has_wayland,
        "pynput_available": pynput_available,
        "pynput_error": pynput_error,
        "keyboard_available": keyboard_available,
        "keyboard_error": keyboard_error,
        "tkinter_available": tk_available,
        "tkinter_error": tk_error,
        "pyqt6_available": pyqt_available,
        "pyqt6_error": pyqt_error,
        "pygobject_available": pygobject_ok,
        "pygobject_error": pygobject_error,
        "native_gui_backend": native_gui_backend,
        "web_gui_fallback_available": True,
        "global_hotkeys_available": global_hotkeys_available,
        "global_hotkey_status": global_hotkey_status,
        "global_hotkey_reason": reason,
        "scroll_lock_reliable_linux_launcher": False,
        "scroll_lock_note": "ScrollLock is preserved as Windows-equivalent intent only. Do not depend on it as the only Linux launcher.",
        "typed_expansion_triggers_required": False,
        "espanso_is_main_workflow": False,
        "product": spec.product_name if spec else "",
    }


def terminal_copy_result_log_line(result: Any) -> str:
    """Return a compact runtime log line for Copy Terminal Buffer provider results."""
    return (
        "COPY_TERMINAL_BUFFER result "
        f"ok={result.ok} "
        f"provider={result.provider} "
        f"quality={result.quality} "
        f"text_length={len(result.text)} "
        f"message={result.message}"
    )


class RuntimeModel:
    def __init__(self, spec: BoardSpec, clipboard: Clipboard) -> None:
        self.spec = spec
        self.clipboard = clipboard
        self.profile_index = 0
        self.board_index = 0
        self.status = "Ready"

    def copy_prompt_slot(self, slot: int) -> str:
        prompt = self.spec.prompt(self.profile_index, self.board_index, slot)
        body = self.spec.prompt_body(prompt)
        self.clipboard.copy(body)
        self.status = f"Copied: {slot} {prompt.label}"
        return body

    def paste_prompt_slot(self, slot: int) -> str:
        body = self.copy_prompt_slot(slot)
        self.status = f"Paste target unavailable; copied: {slot} {self.spec.prompt(self.profile_index, self.board_index, slot).label}"
        return body

    def copy_terminal_buffer(self, provider: Any = copy_terminal_buffer_with_provider) -> str:
        """Copy terminal text through the provider path used by the board button."""
        print("COPY_TERMINAL_BUFFER button_entry", flush=True)

        try:
            result = provider()
        except Exception as exc:  # noqa: BLE001 - button path must surface failures.
            self.status = f"ERROR: Copy Terminal Buffer provider failed: {exc}"
            print(
                "COPY_TERMINAL_BUFFER provider_exception "
                f"exception={type(exc).__name__} message={exc}",
                flush=True,
            )
            return ""

        print(terminal_copy_result_log_line(result), flush=True)

        if result.ok and result.text.strip():
            try:
                clipboard_backend = copy_terminal_text_to_system_clipboard(result.text, self.clipboard)
                print(
                    f"COPY_TERMINAL_BUFFER clipboard_written backend={clipboard_backend} text_length={len(result.text or '')}",
                    flush=True,
                )
            except Exception as exc:  # noqa: BLE001 - clipboard failures must be visible.
                self.status = f"ERROR: Copy Terminal Buffer clipboard write failed: {exc}"
                print(
                    "COPY_TERMINAL_BUFFER clipboard_exception "
                    f"provider={result.provider} quality={result.quality} "
                    f"exception={type(exc).__name__} message={exc}",
                    flush=True,
                )
                return ""

            self.status = result.message
            return result.text

        message = result.message
        if not message.startswith(("UNSUPPORTED:", "ERROR:")):
            message = (
                f"UNSUPPORTED: terminal provider returned {result.quality}; "
                f"clipboard was not changed. {result.message}"
            )

        self.status = message
        print(
            "COPY_TERMINAL_BUFFER not_copied "
            f"provider={result.provider} quality={result.quality} message={message}",
            flush=True,
        )
        return ""

    def cycle_profile(self) -> None:
        self.profile_index = (self.profile_index + 1) % max(1, len(self.spec.profiles))
        self.status = f"Profile: {self.spec.profiles[self.profile_index]['name']}"

    def set_profile(self, profile_index: int) -> None:
        if profile_index < 0 or profile_index >= len(self.spec.profiles):
            raise IndexError("profile_index out of range")
        self.profile_index = profile_index
        self.status = f"Profile: {self.spec.profiles[profile_index]['name']}"

    def cycle_board(self) -> None:
        self.board_index = (self.board_index + 1) % max(1, len(self.spec.boards))
        self.status = f"Board: {self.spec.boards[self.board_index]['name']}"

    def set_board(self, board_index: int) -> None:
        if board_index < 0 or board_index >= len(self.spec.boards):
            raise IndexError("board_index out of range")
        self.board_index = board_index
        self.status = f"Board: {self.spec.boards[board_index]['name']}"

    def active_title(self) -> str:
        profile = self.spec.profiles[self.profile_index]
        board = self.spec.boards[self.board_index]
        return f"{profile['name']} — {board['name']}"


def tkinter_available() -> tuple[bool, str]:
    try:
        import tkinter  # type: ignore  # noqa: F401
        return True, ""
    except Exception as exc:  # noqa: BLE001
        return False, str(exc)


def pyqt6_available() -> tuple[bool, str]:
    try:
        import PyQt6.QtWidgets  # type: ignore  # noqa: F401
        return True, ""
    except Exception as exc:  # noqa: BLE001
        return False, str(exc)


def pygobject_available() -> tuple[bool, str]:
    try:
        import gi  # type: ignore  # noqa: F401
        return True, ""
    except Exception as exc:  # noqa: BLE001
        return False, str(exc)


def choose_clipboard(name: str, root: Any | None = None) -> Clipboard:
    if name == "memory":
        return MemoryClipboard()
    if name == "tk" and root is not None:
        return TkClipboard(root)
    if name == "external":
        return ExternalClipboard()
    if root is not None:
        return TkClipboard(root)
    return ExternalClipboard()



def konsole_dbus_services() -> list[str]:
    """Return active Konsole DBus service names."""
    if not shutil.which("qdbus"):
        return []
    proc = subprocess.run(["qdbus"], check=False, capture_output=True, text=True)
    if proc.returncode != 0:
        return []
    services = []
    for line in proc.stdout.splitlines():
        service = line.strip()
        if service.startswith("org.kde.konsole-"):
            services.append(service)
    return services


def konsole_session_objects(service: str) -> list[str]:
    """Return Konsole /Sessions/N DBus object paths for a service."""
    proc = subprocess.run(["qdbus", service], check=False, capture_output=True, text=True)
    if proc.returncode != 0:
        return []

    objects = []
    for line in proc.stdout.splitlines():
        obj = line.strip()
        if obj.startswith("/Sessions/"):
            objects.append(obj)

    def session_sort_key(obj: str) -> tuple[int, str]:
        try:
            return (int(obj.rsplit("/", 1)[1]), obj)
        except Exception:
            return (999999, obj)

    return sorted(objects, key=session_sort_key)


class QtClipboard:
    def __init__(self, app: Any) -> None:
        self.app = app

    def copy(self, text: str) -> None:
        self.app.clipboard().setText(text)

    def paste(self) -> str:
        return self.app.clipboard().text()


class QtPromptForgeDialog:
    def __init__(self, parent: Any, clipboard: Clipboard) -> None:
        from PyQt6.QtCore import Qt
        from PyQt6.QtWidgets import (
            QCheckBox,
            QComboBox,
            QDialog,
            QGridLayout,
            QLabel,
            QPushButton,
            QTextEdit,
            QVBoxLayout,
        )

        self.Qt = Qt
        self.dialog = QDialog(parent)
        self.dialog.setWindowTitle("Prompt Forge")
        self.dialog.resize(560, 560)
        self.clipboard = clipboard
        self.prompt_b_visible = False

        layout = QVBoxLayout()
        self.dialog.setLayout(layout)
        title = QLabel("Prompt Forge")
        title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(title)

        coach = QPushButton("Copy Prompt Coach")
        coach.clicked.connect(self.copy_prompt_coach)
        layout.addWidget(coach)

        grid = QGridLayout()
        layout.addLayout(grid)
        grid.addWidget(QLabel("Source Mode:"), 0, 0)
        self.source_mode = QComboBox()
        self.source_mode.addItems(["Manual Paste"])
        grid.addWidget(self.source_mode, 0, 1)
        grid.addWidget(QLabel("Transformation:"), 1, 0)
        self.transform = QComboBox()
        self.transform.addItems(FORGE_TRANSFORMATIONS)
        self.transform.currentTextChanged.connect(self.transform_changed)
        grid.addWidget(self.transform, 1, 1)
        grid.addWidget(QLabel("Output:"), 2, 0)
        self.output_mode = QComboBox()
        self.output_mode.addItems(["Copy to clipboard"])
        grid.addWidget(self.output_mode, 2, 1)

        layout.addWidget(QLabel("Extra Instructions (optional)"))
        self.extra = QTextEdit()
        self.extra.setFixedHeight(64)
        layout.addWidget(self.extra)
        layout.addWidget(QLabel("Prompt A / Main Source"))
        self.prompt_a = QTextEdit()
        self.prompt_a.setFixedHeight(120)
        layout.addWidget(self.prompt_a)

        self.add_b_button = QPushButton("+ Add Prompt B")
        self.add_b_button.clicked.connect(self.show_prompt_b)
        layout.addWidget(self.add_b_button)
        self.prompt_b_label = QLabel("Prompt B / Optional Second Source")
        self.prompt_b = QTextEdit()
        self.prompt_b.setFixedHeight(100)
        self.prompt_b_label.hide()
        self.prompt_b.hide()
        layout.addWidget(self.prompt_b_label)
        layout.addWidget(self.prompt_b)

        buttons = QGridLayout()
        layout.addLayout(buttons)
        build = QPushButton("Build and Copy")
        build.clicked.connect(self.build_and_copy)
        buttons.addWidget(build, 0, 0)
        close = QPushButton("Close")
        close.clicked.connect(self.dialog.close)
        buttons.addWidget(close, 0, 1)
        self.keep_open = QCheckBox("Keep Prompt Forge open after build")
        layout.addWidget(self.keep_open)
        self.status = QLabel("Ready")
        layout.addWidget(self.status)

    def show(self) -> None:
        self.dialog.show()
        self.dialog.raise_()
        self.dialog.activateWindow()

    def show_prompt_b(self) -> None:
        if self.prompt_b_visible:
            return
        self.prompt_b_visible = True
        self.add_b_button.hide()
        self.prompt_b_label.show()
        self.prompt_b.show()

    def transform_changed(self, text: str) -> None:
        if text == "Merge / Combine":
            self.show_prompt_b()

    def copy_prompt_coach(self) -> None:
        self.clipboard.copy(PROMPT_COACH_TEXT)
        self.status.setText("Prompt Coach copied to clipboard.")

    def build_and_copy(self) -> None:
        transformation = self.transform.currentText() or "Merge / Combine"
        extra = self.extra.toPlainText().strip()
        prompt_a = self.prompt_a.toPlainText().strip()
        prompt_b = self.prompt_b.toPlainText().strip() if self.prompt_b_visible else ""
        if not prompt_a:
            self.status.setText("Prompt A is required for Build and Copy.")
            return
        output = [
            "Task:",
            "Create a finished reusable prompt from the source material below.",
            "",
            "Selected transformation:",
            transformation,
            "",
            "Extra instructions:",
            extra,
            "",
            "Prompt A / Main Source:",
            "---",
            prompt_a,
            "---",
            "",
        ]
        if prompt_b:
            output.extend(["Prompt B / Optional Second Source:", "---", prompt_b, "---", ""])
        output.extend(
            [
                "Output requirements:",
                "- Produce one complete prompt, not commentary about the prompt.",
                "- Preserve useful constraints from the source material.",
                "- Remove duplication and conflicting wording.",
                "- Resolve conflicts explicitly when Prompt A and Prompt B disagree.",
                "- Keep the final prompt ready to paste into an AI session.",
                "- Do not include placeholder text.",
            ]
        )
        self.clipboard.copy("\n".join(output))
        self.status.setText("Built and copied to clipboard.")
        if not self.keep_open.isChecked():
            self.dialog.close()


class QtBoardGui:
    """Native compact Qt board used when PyQt6 is already available."""

    def __init__(self, spec: BoardSpec, settings: SettingsStore, clipboard_name: str = "auto") -> None:
        from PyQt6.QtCore import QEvent, QObject, Qt
        from PyQt6.QtWidgets import (
            QApplication,
            QCheckBox,
            QDialog,
            QFrame,
            QGridLayout,
            QLabel,
            QPushButton,
            QVBoxLayout,
            QWidget,
        )

        class BoardKeyFilter(QObject):
            def __init__(self, owner: "QtBoardGui") -> None:
                super().__init__()
                self.owner = owner

            def eventFilter(self, obj: Any, event: Any) -> bool:
                if event.type() == QEvent.Type.KeyPress and self.owner.handle_key_press(event):
                    return True
                return super().eventFilter(obj, event)

        self.Qt = Qt
        self.QApplication = QApplication
        self.QDialog = QDialog
        self.QGridLayout = QGridLayout
        self.QLabel = QLabel
        self.QPushButton = QPushButton
        self.app = QApplication.instance() or QApplication(sys.argv[:1])
        self.key_filter = BoardKeyFilter(self)
        self.app.installEventFilter(self.key_filter)
        self.spec = spec
        self.settings = settings
        self.window = QWidget()
        self.window.setWindowTitle(spec.product_name)
        self.window.resize(390, 430)
        self.window.setMinimumWidth(360)
        self.clipboard = MemoryClipboard() if clipboard_name == "memory" else QtClipboard(self.app)
        self.model = RuntimeModel(spec, self.clipboard)
        self.numpad_enabled = settings.enabled("enable_numpad_mode")
        self.prompt_buttons: list[Any] = []
        self._build_board(QVBoxLayout, QGridLayout, QLabel, QPushButton, QCheckBox, QFrame)
        self._refresh_board()

    def _build_board(self, QVBoxLayout: Any, QGridLayout: Any, QLabel: Any, QPushButton: Any, QCheckBox: Any, QFrame: Any) -> None:
        Qt = self.Qt
        layout = QVBoxLayout()
        layout.setContentsMargins(14, 12, 14, 12)
        layout.setSpacing(7)
        self.window.setLayout(layout)

        title = QLabel(self.spec.product_name)
        title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(title)
        self.profile_board_label = QLabel("")
        self.profile_board_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self.profile_board_label)
        self.status_label = QLabel("")
        self.status_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(self.status_label)

        top = QGridLayout()
        layout.addLayout(top)
        switch_profile = QPushButton("Switch Profile")
        switch_profile.clicked.connect(self.open_profile_chooser)
        top.addWidget(switch_profile, 0, 0)
        open_prompts = QPushButton("Open Prompts")
        open_prompts.clicked.connect(self.open_prompts)
        top.addWidget(open_prompts, 0, 1)

        self.numpad_check = QCheckBox("Enable Numpad Mode")
        self.numpad_check.setChecked(self.settings.enabled("enable_numpad_mode"))
        self.numpad_check.toggled.connect(self.toggle_numpad)
        top.addWidget(self.numpad_check, 1, 0)
        self.remember_numpad_check = QCheckBox("Remember Numpad Mode")
        self.remember_numpad_check.setChecked(self.settings.enabled("remember_numpad_mode"))
        self.remember_numpad_check.toggled.connect(self.toggle_remember_numpad)
        top.addWidget(self.remember_numpad_check, 1, 1)

        line = QFrame()
        line.setFrameShape(QFrame.Shape.HLine)
        line.setFrameShadow(QFrame.Shadow.Sunken)
        layout.addWidget(line)

        prompt_grid = QGridLayout()
        prompt_grid.setHorizontalSpacing(10)
        prompt_grid.setVerticalSpacing(8)
        layout.addLayout(prompt_grid)
        for slot in range(1, self.spec.prompts_per_board + 1):
            button = QPushButton("")
            button.clicked.connect(lambda _checked=False, current_slot=slot: self.copy_prompt(current_slot))
            row = (slot - 1) // 2
            col = (slot - 1) % 2
            prompt_grid.addWidget(button, row, col)
            self.prompt_buttons.append(button)

        copy_terminal = QPushButton("Copy Terminal Buffer")
        copy_terminal.clicked.connect(self.copy_terminal_buffer)
        layout.addWidget(copy_terminal)

        bottom = QGridLayout()
        layout.addLayout(bottom)
        close = QPushButton("Close")
        close.clicked.connect(self.close_board)
        bottom.addWidget(close, 0, 0)
        forge = QPushButton("Prompt Forge")
        forge.clicked.connect(self.open_prompt_forge)
        bottom.addWidget(forge, 0, 1)

    def _refresh_board(self) -> None:
        profile = self.spec.profiles[self.model.profile_index]
        board = self.spec.boards[self.model.board_index]
        self.profile_board_label.setText(f"{profile['name']} — {board['name']}")
        if not self.model.status or self.model.status == "Ready":
            self.status_label.setText(f"Numpad: {'On' if self.numpad_enabled else 'Off'}")
        else:
            self.status_label.setText(self.model.status)
        for slot, button in enumerate(self.prompt_buttons, start=1):
            try:
                prompt = self.spec.prompt(self.model.profile_index, self.model.board_index, slot)
                button.setText(f"{slot} {prompt.label}")
                button.setEnabled(True)
            except Exception:  # noqa: BLE001
                button.setText(f"{slot} [missing]")
                button.setEnabled(False)

    def set_status(self, text: str) -> None:
        self.model.status = text
        self.status_label.setText(text)

    def handle_key_press(self, event: Any) -> bool:
        key = event.key()
        pause_keys = {self.Qt.Key.Key_Pause}
        break_key = getattr(self.Qt.Key, "Key_Break", None)
        if break_key is not None:
            pause_keys.add(break_key)

        if key == self.Qt.Key.Key_NumLock:
            self.cycle_profile_from_keyboard()
            return True

        if key in pause_keys:
            self.cycle_board_from_keyboard()
            return True

        return False

    def cycle_profile_from_keyboard(self) -> None:
        self.model.cycle_profile()
        self._refresh_board()

    def cycle_board_from_keyboard(self) -> None:
        self.model.cycle_board()
        self._refresh_board()

    def copy_prompt(self, slot: int) -> None:
        try:
            self.model.copy_prompt_slot(slot)
            self._refresh_board()
        except Exception as exc:  # noqa: BLE001
            self.set_status(f"ERROR: {exc}")

    def open_prompts(self) -> None:
        try:
            prompt = self.spec.prompt(self.model.profile_index, self.model.board_index, 1)
            folder = (self.spec.repo_root / prompt.path).parent
            subprocess.Popen(["xdg-open", str(folder)])
            self.set_status(f"Opened prompt folder: {folder}")
        except Exception as exc:  # noqa: BLE001
            self.set_status(f"ERROR: could not open prompt folder: {exc}")

    def toggle_numpad(self, enabled: bool) -> None:
        self.numpad_enabled = bool(enabled)
        if self.remember_numpad_check.isChecked():
            self.settings.set_enabled("enable_numpad_mode", self.numpad_enabled)
        else:
            self.settings.values["enable_numpad_mode"] = "1" if self.numpad_enabled else "0"
        self.set_status(f"Numpad: {'On' if self.numpad_enabled else 'Off'}")

    def toggle_remember_numpad(self, remember: bool) -> None:
        remember = bool(remember)
        self.settings.set_enabled("remember_numpad_mode", remember)
        if remember:
            self.settings.set_enabled("enable_numpad_mode", self.numpad_enabled)
        self.set_status(f"Remember Numpad Mode: {'On' if remember else 'Off'}")

    def copy_terminal_buffer(self) -> None:
        try:
            self.model.copy_terminal_buffer()
        except Exception as exc:  # noqa: BLE001 - GUI callbacks must not fail silently.
            print(
                "COPY_TERMINAL_BUFFER button_exception "
                f"backend={type(self).__name__} exception={type(exc).__name__} message={exc}",
                flush=True,
            )
            self.set_status(f"ERROR: Copy Terminal Buffer failed: {exc}")
            return

        self._refresh_board()

    def open_profile_chooser(self) -> None:
        dialog = self.QDialog(self.window)
        dialog.setWindowTitle(f"{self.spec.product_name} - Switch Profile")
        grid = self.QGridLayout()
        dialog.setLayout(grid)
        label = self.QLabel("Switch Profile")
        label.setAlignment(self.Qt.AlignmentFlag.AlignCenter)
        grid.addWidget(label, 0, 0)

        def choose(index: int) -> None:
            self.model.set_profile(index)
            dialog.close()
            self._refresh_board()

        for index, profile in enumerate(self.spec.profiles):
            button = self.QPushButton(profile["name"])
            button.clicked.connect(lambda _checked=False, idx=index: choose(idx))
            grid.addWidget(button, index + 1, 0)
        close = self.QPushButton("Close")
        close.clicked.connect(dialog.close)
        grid.addWidget(close, len(self.spec.profiles) + 1, 0)
        dialog.show()

    def open_prompt_forge(self) -> None:
        self.forge = QtPromptForgeDialog(self.window, self.clipboard)
        self.forge.show()

    def close_board(self) -> None:
        self.window.close()
        self.app.quit()

    def run(self) -> None:
        print("## Linux Hotkey Board Native Qt GUI")
        print(f"Product: {self.spec.product_name}")
        print("Backend: PyQt6")
        print("Close the board with the Close button, or press Ctrl+C in this terminal.")
        self.window.show()
        self.app.exec()



class WebBoardApp:
    """Dependency-free browser GUI fallback for systems without tkinter.

    This is still a local hotkey-board GUI. It serves only on 127.0.0.1 and
    uses the browser clipboard from a real button click. No AI calls and no
    network service beyond localhost are involved.
    """

    def __init__(self, spec: BoardSpec, settings: SettingsStore, clipboard_name: str = "auto") -> None:
        self.spec = spec
        self.settings = settings
        self.clipboard = choose_clipboard("memory" if clipboard_name == "memory" else "external")
        self.model = RuntimeModel(spec, self.clipboard)
        self.server: ThreadingHTTPServer | None = None
        self.url = ""

    def _json_response(self, handler: BaseHTTPRequestHandler, payload: dict[str, Any], status: int = 200) -> None:
        data = json.dumps(payload).encode("utf-8")
        handler.send_response(status)
        handler.send_header("Content-Type", "application/json; charset=utf-8")
        handler.send_header("Content-Length", str(len(data)))
        handler.end_headers()
        handler.wfile.write(data)

    def _html_response(self, handler: BaseHTTPRequestHandler, body: str, status: int = 200) -> None:
        data = body.encode("utf-8")
        handler.send_response(status)
        handler.send_header("Content-Type", "text/html; charset=utf-8")
        handler.send_header("Content-Length", str(len(data)))
        handler.end_headers()
        handler.wfile.write(data)

    def _active_prompts(self) -> list[dict[str, Any]]:
        prompts = []
        for slot in range(1, self.spec.prompts_per_board + 1):
            try:
                prompt = self.spec.prompt(self.model.profile_index, self.model.board_index, slot)
                prompts.append({"slot": slot, "label": prompt.label, "path": prompt.path})
            except Exception:  # noqa: BLE001
                prompts.append({"slot": slot, "label": "[missing]", "path": "", "missing": True})
        return prompts

    def page(self) -> str:
        prompts = self._active_prompts()
        prompt_buttons = "\n".join(
            f'<button class="prompt" onclick="copyPrompt({item["slot"]})" {"disabled" if item.get("missing") else ""}>'
            f'{item["slot"]} {html.escape(str(item["label"]))}</button>'
            for item in prompts
        )
        profile_options = "\n".join(
            f'<option value="{idx}" {"selected" if idx == self.model.profile_index else ""}>{html.escape(profile["name"])}</option>'
            for idx, profile in enumerate(self.spec.profiles)
        )
        board_options = "\n".join(
            f'<option value="{idx}" {"selected" if idx == self.model.board_index else ""}>{html.escape(board["name"])}</option>'
            for idx, board in enumerate(self.spec.boards)
        )
        transformations = "\n".join(f'<option>{html.escape(item)}</option>' for item in FORGE_TRANSFORMATIONS)
        prompt_coach_json = json.dumps(PROMPT_COACH_TEXT)
        product = html.escape(self.spec.product_name)
        active = html.escape(self.model.active_title())
        status = html.escape(self.model.status)
        numpad_checked = "checked" if self.settings.enabled("enable_numpad_mode") else ""
        remember_checked = "checked" if self.settings.enabled("remember_numpad_mode") else ""
        return f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{product}</title>
<style>
body {{ font-family: sans-serif; margin: 24px; max-width: 780px; }}
header {{ text-align: center; margin-bottom: 12px; }}
button, select {{ font-size: 15px; padding: 8px; margin: 4px; }}
.prompt {{ display: block; width: 100%; text-align: left; }}
.row {{ display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }}
.row > * {{ flex: 1; }}
.status {{ border: 1px solid #aaa; padding: 8px; margin: 10px 0; min-height: 1.4em; }}
textarea {{ width: 100%; min-height: 110px; }}
#forge {{ display: none; border-top: 1px solid #aaa; margin-top: 20px; padding-top: 16px; }}
#promptBWrap {{ display: none; }}
.small {{ font-size: 13px; color: #555; }}
</style>
</head>
<body>
<header>
<h1>{product}</h1>
<div id="active">{active}</div>
<div id="status" class="status">{status}</div>
</header>

<div class="row">
<button onclick="switchProfile()">Switch Profile</button>
<button onclick="openPrompts()">Open Prompts</button>
</div>
<div class="row">
<label>Profile <select id="profileSelect" onchange="setProfile(this.value)">{profile_options}</select></label>
<label>Board <select id="boardSelect" onchange="setBoard(this.value)">{board_options}</select></label>
</div>
<div class="row">
<label><input id="numpad" type="checkbox" onchange="toggleNumpad(this.checked)" {numpad_checked}> Enable Numpad Mode</label>
<label><input id="rememberNumpad" type="checkbox" onchange="toggleRememberNumpad(this.checked)" {remember_checked}> Remember Numpad Mode</label>
</div>
<hr>
<div id="prompts">{prompt_buttons}</div>
<button class="prompt" onclick="copyTerminalBuffer()">Copy Terminal Buffer</button>
<div class="row">
<button onclick="closeBoard()">Close</button>
<button onclick="showForge()">Prompt Forge</button>
</div>
<p class="small">Local browser fallback GUI. It is used when Python tkinter is unavailable. Prompt buttons use browser clipboard permission from the click.</p>
<textarea id="manualCopy" style="display:none"></textarea>

<section id="forge">
<h2>Prompt Forge</h2>
<button onclick="copyText({prompt_coach_json}, 'Prompt Coach copied to clipboard.')">Copy Prompt Coach</button>
<label>Source Mode <select><option>Manual Paste</option></select></label>
<label>Transformation <select id="transform" onchange="transformChanged()">{transformations}</select></label>
<label>Output <select><option>Copy to clipboard</option></select></label>
<label>Extra Instructions (optional)</label>
<textarea id="extra"></textarea>
<label>Prompt A / Main Source</label>
<textarea id="promptA"></textarea>
<div id="addB"><button onclick="showPromptB()">+ Add Prompt B</button></div>
<div id="promptBWrap"><label>Prompt B / Optional Second Source</label><textarea id="promptB"></textarea></div>
<div class="row"><button onclick="buildForge()">Build and Copy</button><button onclick="hideForge()">Close Prompt Forge</button></div>
<label><input id="keepForge" type="checkbox"> Keep Prompt Forge open after build</label>
</section>

<script>
function setStatus(text) {{ document.getElementById('status').textContent = text; }}
async function api(path) {{ const r = await fetch(path); return await r.json(); }}
async function copyText(text, okStatus) {{
  try {{
    if (navigator.clipboard && window.isSecureContext) {{ await navigator.clipboard.writeText(text); }}
    else {{
      const t = document.getElementById('manualCopy');
      t.style.display = 'block'; t.value = text; t.focus(); t.select(); document.execCommand('copy'); t.style.display = 'none';
    }}
    setStatus(okStatus);
  }} catch (err) {{
    const t = document.getElementById('manualCopy');
    t.style.display = 'block'; t.value = text; t.focus(); t.select();
    setStatus('Clipboard permission failed. Text is selected in the manual copy box; press Ctrl+C.');
  }}
}}
async function copyPrompt(slot) {{
  const data = await api('/api/prompt?slot=' + encodeURIComponent(slot));
  await copyText(data.body, data.status);
}}
async function switchProfile() {{ await api('/api/switch-profile'); location.reload(); }}
async function setProfile(i) {{ await api('/api/set-profile?index=' + encodeURIComponent(i)); location.reload(); }}
async function setBoard(i) {{ await api('/api/set-board?index=' + encodeURIComponent(i)); location.reload(); }}
async function toggleNumpad(v) {{ const d = await api('/api/toggle-numpad?enabled=' + (v ? '1':'0')); setStatus(d.status); }}
async function toggleRememberNumpad(v) {{ const d = await api('/api/toggle-remember-numpad?enabled=' + (v ? '1':'0')); setStatus(d.status); }}
async function openPrompts() {{ const d = await api('/api/open-prompts'); setStatus(d.status); }}
function copyTerminalBuffer() {{ setStatus('Copy Terminal Buffer requires the native Qt or Tk Linux board backend.'); }}
async function closeBoard() {{ await api('/api/shutdown'); window.close(); document.body.innerHTML = '<h1>Board closed</h1>'; }}
function showForge() {{ document.getElementById('forge').style.display = 'block'; }}
function hideForge() {{ document.getElementById('forge').style.display = 'none'; document.getElementById('promptA').value=''; document.getElementById('promptB').value=''; document.getElementById('extra').value=''; document.getElementById('promptBWrap').style.display='none'; document.getElementById('addB').style.display='block'; }}
function showPromptB() {{ document.getElementById('promptBWrap').style.display='block'; document.getElementById('addB').style.display='none'; }}
function transformChanged() {{ if (document.getElementById('transform').value === 'Merge / Combine') showPromptB(); }}
function buildForge() {{
  const a = document.getElementById('promptA').value.trim();
  const b = document.getElementById('promptB').value.trim();
  const extra = document.getElementById('extra').value.trim();
  const transform = document.getElementById('transform').value || 'Merge / Combine';
  if (!a) {{ setStatus('Prompt A is required for Build and Copy.'); return; }}
  let out = 'Task:\nCreate a finished reusable prompt from the source material below.\n\nSelected transformation:\n' + transform + '\n\nExtra instructions:\n' + extra + '\n\nPrompt A / Main Source:\n---\n' + a + '\n---\n\n';
  if (b) out += 'Prompt B / Optional Second Source:\n---\n' + b + '\n---\n\n';
  out += 'Output requirements:\n- Produce one complete prompt, not commentary about the prompt.\n- Preserve useful constraints from the source material.\n- Remove duplication and conflicting wording.\n- Resolve conflicts explicitly when Prompt A and Prompt B disagree.\n- Keep the final prompt ready to paste into an AI session.\n- Do not include placeholder text.';
  copyText(out, 'Built and copied to clipboard.');
  if (!document.getElementById('keepForge').checked) hideForge();
}}
document.addEventListener('keydown', function(e) {{
  if (e.key >= '1' && e.key <= '8') copyPrompt(e.key);
  if (e.key === 'Escape') closeBoard();
}});
</script>
</body>
</html>"""

    def handle_path(self, handler: BaseHTTPRequestHandler) -> None:
        parsed = urlparse(handler.path)
        qs = parse_qs(parsed.query)
        try:
            if parsed.path == "/":
                self._html_response(handler, self.page())
                return
            if parsed.path == "/api/prompt":
                slot = int(qs.get("slot", ["1"])[0])
                prompt = self.spec.prompt(self.model.profile_index, self.model.board_index, slot)
                body = self.spec.prompt_body(prompt)
                self.model.status = f"Copied: {slot} {prompt.label}"
                self._json_response(handler, {"body": body, "status": self.model.status})
                return
            if parsed.path == "/api/switch-profile":
                self.model.set_profile((self.model.profile_index + 1) % len(self.spec.profiles))
                self._json_response(handler, {"status": self.model.status})
                return
            if parsed.path == "/api/set-profile":
                self.model.set_profile(int(qs.get("index", ["0"])[0]))
                self._json_response(handler, {"status": self.model.status})
                return
            if parsed.path == "/api/set-board":
                self.model.set_board(int(qs.get("index", ["0"])[0]))
                self._json_response(handler, {"status": self.model.status})
                return
            if parsed.path == "/api/toggle-numpad":
                enabled = qs.get("enabled", ["0"])[0] == "1"
                if self.settings.enabled("remember_numpad_mode"):
                    self.settings.set_enabled("enable_numpad_mode", enabled)
                else:
                    self.settings.values["enable_numpad_mode"] = "1" if enabled else "0"
                self.model.status = f"Numpad: {'On' if enabled else 'Off'}"
                self._json_response(handler, {"status": self.model.status})
                return
            if parsed.path == "/api/toggle-remember-numpad":
                enabled = qs.get("enabled", ["0"])[0] == "1"
                self.settings.set_enabled("remember_numpad_mode", enabled)
                self.model.status = f"Remember Numpad Mode: {'On' if enabled else 'Off'}"
                self._json_response(handler, {"status": self.model.status})
                return
            if parsed.path == "/api/open-prompts":
                prompt = self.spec.prompt(self.model.profile_index, self.model.board_index, 1)
                folder = self.spec.repo_root / prompt.path
                subprocess.Popen(["xdg-open", str(folder.parent)])
                self.model.status = f"Opened prompt folder: {folder.parent}"
                self._json_response(handler, {"status": self.model.status})
                return
            if parsed.path == "/api/shutdown":
                self._json_response(handler, {"status": "Board closed"})
                if self.server is not None:
                    threading.Thread(target=self.server.shutdown, daemon=True).start()
                return
            self._json_response(handler, {"error": "not found"}, status=404)
        except Exception as exc:  # noqa: BLE001
            self._json_response(handler, {"error": str(exc), "status": f"ERROR: {exc}"}, status=500)

    def run(self) -> None:
        app = self

        class Handler(BaseHTTPRequestHandler):
            def do_GET(self) -> None:  # noqa: N802 - stdlib callback name.
                app.handle_path(self)

            def log_message(self, _format: str, *args: Any) -> None:
                return

        self.server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self.server.app = self  # type: ignore[attr-defined]
        port = int(self.server.server_address[1])
        self.url = f"http://127.0.0.1:{port}/"
        print("## Linux Hotkey Board Web GUI")
        print(f"Product: {self.spec.product_name}")
        print(f"URL: {self.url}")
        print("Tkinter is unavailable, so the runtime opened a local browser GUI fallback.")
        print("Close the board from the browser Close button, or press Ctrl+C in this terminal.")
        webbrowser.open(self.url)
        try:
            self.server.serve_forever()
        except KeyboardInterrupt:
            pass
        finally:
            self.server.server_close()


class BoardGui:
    def __init__(self, spec: BoardSpec, settings: SettingsStore, clipboard_name: str = "auto") -> None:
        try:
            import tkinter as tk
            from tkinter import ttk
        except Exception as exc:  # noqa: BLE001
            raise RuntimeError(f"tkinter is required for the GUI board but could not be imported: {exc}") from exc

        self.tk = tk
        self.ttk = ttk
        self.spec = spec
        self.settings = settings
        self.root = tk.Tk()
        self.root.title(spec.product_name)
        self.clipboard = choose_clipboard(clipboard_name, self.root)
        self.model = RuntimeModel(spec, self.clipboard)
        self.status_var = tk.StringVar(value="Ready")
        self.profile_board_var = tk.StringVar(value="")
        self.numpad_var = tk.BooleanVar(value=settings.enabled("enable_numpad_mode"))
        self.remember_numpad_var = tk.BooleanVar(value=settings.enabled("remember_numpad_mode"))
        self._build_board()
        self._refresh_board()

    def _build_board(self) -> None:
        tk = self.tk
        ttk = self.ttk
        frame = ttk.Frame(self.root, padding=12)
        frame.grid(row=0, column=0, sticky="nsew")
        self.root.columnconfigure(0, weight=1)
        frame.columnconfigure(0, weight=1)
        frame.columnconfigure(1, weight=1)

        title = ttk.Label(frame, text=self.spec.product_name, anchor="center")
        title.grid(row=0, column=0, columnspan=2, sticky="ew")
        subtitle = ttk.Label(frame, textvariable=self.profile_board_var, anchor="center")
        subtitle.grid(row=1, column=0, columnspan=2, sticky="ew", pady=(4, 0))
        status = ttk.Label(frame, textvariable=self.status_var, anchor="center", width=72, wraplength=620, justify="center")
        status.grid(row=2, column=0, columnspan=2, sticky="ew", pady=(4, 8))

        ttk.Button(frame, text="Switch Profile", command=self.open_profile_chooser).grid(row=3, column=0, sticky="ew", padx=(0, 4))
        ttk.Button(frame, text="Open Prompts", command=self.open_prompts).grid(row=3, column=1, sticky="ew", padx=(4, 0))

        ttk.Checkbutton(frame, text="Enable Numpad Mode", variable=self.numpad_var, command=self.toggle_numpad).grid(
            row=4, column=0, sticky="w", pady=(7, 0)
        )
        ttk.Checkbutton(frame, text="Remember Numpad Mode", variable=self.remember_numpad_var, command=self.toggle_remember_numpad).grid(
            row=4, column=1, sticky="w", pady=(7, 0)
        )

        separator = ttk.Separator(frame)
        separator.grid(row=5, column=0, columnspan=2, sticky="ew", pady=(9, 8))

        self.prompt_buttons: list[Any] = []
        row = 6
        for slot in range(1, self.spec.prompts_per_board + 1):
            button = ttk.Button(frame, command=lambda current_slot=slot: self.copy_prompt(current_slot))
            button.grid(row=row, column=0, columnspan=2, sticky="ew", pady=2)
            self.prompt_buttons.append(button)
            row += 1

        ttk.Button(frame, text="Copy Terminal Buffer", command=self.copy_terminal_buffer).grid(
            row=row, column=0, columnspan=2, sticky="ew", pady=(10, 2)
        )
        row += 1
        ttk.Button(frame, text="Close", command=self.close_board).grid(row=row, column=0, sticky="ew", padx=(0, 4), pady=(8, 0))
        ttk.Button(frame, text="Prompt Forge", command=self.open_prompt_forge).grid(row=row, column=1, sticky="ew", padx=(4, 0), pady=(8, 0))

        self.root.bind("<Escape>", lambda _event: self.close_board())
        self.root.bind_all("<KeyPress>", self.handle_key_press, add="+")
        for slot in range(1, min(9, self.spec.prompts_per_board + 1)):
            self.root.bind(str(slot), lambda _event, current_slot=slot: self.copy_prompt(current_slot))

    def _refresh_board(self) -> None:
        profile = self.spec.profiles[self.model.profile_index]
        board = self.spec.boards[self.model.board_index]
        self.profile_board_var.set(f"{profile['name']} — {board['name']}")
        for slot, button in enumerate(self.prompt_buttons, start=1):
            try:
                prompt = self.spec.prompt(self.model.profile_index, self.model.board_index, slot)
                button.configure(text=f"{slot} {prompt.label}", state="normal")
            except Exception:  # noqa: BLE001
                button.configure(text=f"{slot} [missing]", state="disabled")
        self.status_var.set(self.compact_status_text(self.model.status))

    def compact_status_text(self, text: str) -> str:
        text = str(text)

        if text.startswith("UNSUPPORTED:") and "terminal transcript" in text:
            return (
                "UNSUPPORTED: terminal transcript is not active.\n"
                "Open a transcript terminal before using Copy Terminal Buffer."
            )

        if text.startswith("UNSUPPORTED:") and "terminal-emulator scrollback" in text:
            return (
                "UNSUPPORTED: full terminal scrollback copy is not available.\n"
                "Use the VeydraNet/eMachination transcript terminal path."
            )

        if len(text) > 180:
            return text[:177] + "..."

        return text

    def set_status(self, text: str) -> None:
        self.model.status = text
        self.status_var.set(self.compact_status_text(text))

    def handle_key_press(self, event: Any) -> str | None:
        keysym = str(getattr(event, "keysym", ""))
        if keysym in {"Num_Lock", "NumLock"}:
            self.cycle_profile_from_keyboard()
            return "break"

        if keysym in {"Pause", "Break"}:
            self.cycle_board_from_keyboard()
            return "break"

        if bool(self.numpad_var.get()):
            keymap = {
                "KP_1": 1, "KP_End": 1,
                "KP_2": 2, "KP_Down": 2,
                "KP_3": 3, "KP_Next": 3, "KP_Page_Down": 3,
                "KP_4": 4, "KP_Left": 4,
                "KP_5": 5, "KP_Begin": 5,
                "KP_6": 6, "KP_Right": 6,
                "KP_7": 7, "KP_Home": 7,
                "KP_8": 8, "KP_Up": 8,
                "1": 1, "2": 2, "3": 3, "4": 4,
                "5": 5, "6": 6, "7": 7, "8": 8,
            }
            slot = keymap.get(keysym)
            if slot is not None:
                self.copy_prompt(slot)
                return "break"

        return None

    def cycle_profile_from_keyboard(self) -> None:
        self.model.cycle_profile()
        self._refresh_board()

    def cycle_board_from_keyboard(self) -> None:
        self.model.cycle_board()
        self._refresh_board()

    def copy_prompt(self, slot: int) -> None:
        try:
            self.model.copy_prompt_slot(slot)
            self._refresh_board()
        except Exception as exc:  # noqa: BLE001
            self.set_status(f"ERROR: {exc}")

    def open_prompts(self) -> None:
        try:
            prompt = self.spec.prompt(self.model.profile_index, self.model.board_index, 1)
            folder = self.spec.repo_root / prompt.path
            folder = folder.parent
            subprocess.Popen(["xdg-open", str(folder)])
            self.set_status(f"Opened prompt folder: {folder}")
        except Exception as exc:  # noqa: BLE001
            self.set_status(f"ERROR: could not open prompt folder: {exc}")

    def toggle_numpad(self) -> None:
        enabled = bool(self.numpad_var.get())
        if self.remember_numpad_var.get():
            self.settings.set_enabled("enable_numpad_mode", enabled)
        else:
            self.settings.values["enable_numpad_mode"] = "1" if enabled else "0"
        self.set_status(f"Numpad: {'On' if enabled else 'Off'}")

    def toggle_remember_numpad(self) -> None:
        remember = bool(self.remember_numpad_var.get())
        self.settings.set_enabled("remember_numpad_mode", remember)
        if remember:
            self.settings.set_enabled("enable_numpad_mode", bool(self.numpad_var.get()))
        self.set_status(f"Remember Numpad Mode: {'On' if remember else 'Off'}")

    def copy_terminal_buffer(self) -> None:
        try:
            self.model.copy_terminal_buffer()
        except Exception as exc:  # noqa: BLE001 - GUI callbacks must not fail silently.
            print(
                "COPY_TERMINAL_BUFFER button_exception "
                f"backend={type(self).__name__} exception={type(exc).__name__} message={exc}",
                flush=True,
            )
            self.set_status(f"ERROR: Copy Terminal Buffer failed: {exc}")
            return

        self._refresh_board()

    def open_profile_chooser(self) -> None:
        tk = self.tk
        ttk = self.ttk
        chooser = tk.Toplevel(self.root)
        chooser.title(f"{self.spec.product_name} - Switch Profile")
        frame = ttk.Frame(chooser, padding=12)
        frame.grid(row=0, column=0, sticky="nsew")
        ttk.Label(frame, text="Switch Profile", anchor="center").grid(row=0, column=0, sticky="ew")

        def choose(index: int) -> None:
            self.model.set_profile(index)
            chooser.destroy()
            self._refresh_board()

        for index, profile in enumerate(self.spec.profiles):
            ttk.Button(frame, text=profile["name"], command=lambda idx=index: choose(idx)).grid(row=index + 1, column=0, sticky="ew", pady=3)
        ttk.Button(frame, text="Close", command=chooser.destroy).grid(row=len(self.spec.profiles) + 1, column=0, sticky="ew", pady=(8, 0))

    def open_prompt_forge(self) -> None:
        PromptForgeGui(self.root, self.clipboard)

    def close_board(self) -> None:
        self.root.destroy()

    def run(self) -> None:
        self.root.mainloop()


class PromptForgeGui:
    def __init__(self, parent: Any, clipboard: Clipboard) -> None:
        import tkinter as tk
        from tkinter import ttk

        self.tk = tk
        self.ttk = ttk
        self.clipboard = clipboard
        self.window = tk.Toplevel(parent)
        self.window.title("Prompt Forge")
        self.status_var = tk.StringVar(value="Ready")
        self.prompt_b_visible = False
        self._build()

    def _build(self) -> None:
        tk = self.tk
        ttk = self.ttk
        frame = ttk.Frame(self.window, padding=12)
        frame.grid(row=0, column=0, sticky="nsew")
        frame.columnconfigure(0, weight=1)
        frame.columnconfigure(1, weight=1)

        ttk.Label(frame, text="Prompt Forge", anchor="center").grid(row=0, column=0, columnspan=2, sticky="ew")
        ttk.Button(frame, text="Copy Prompt Coach", command=self.copy_prompt_coach).grid(row=1, column=0, columnspan=2, sticky="ew", pady=(8, 8))

        ttk.Label(frame, text="Source Mode:").grid(row=2, column=0, sticky="w")
        self.source_mode = ttk.Combobox(frame, values=["Manual Paste"], state="readonly")
        self.source_mode.current(0)
        self.source_mode.grid(row=2, column=1, sticky="ew")

        ttk.Label(frame, text="Transformation:").grid(row=3, column=0, sticky="w", pady=(5, 0))
        self.transform = ttk.Combobox(frame, values=FORGE_TRANSFORMATIONS, state="readonly")
        self.transform.current(0)
        self.transform.grid(row=3, column=1, sticky="ew", pady=(5, 0))
        self.transform.bind("<<ComboboxSelected>>", lambda _event: self.transform_changed())

        ttk.Label(frame, text="Output:").grid(row=4, column=0, sticky="w", pady=(5, 0))
        self.output_mode = ttk.Combobox(frame, values=["Copy to clipboard"], state="readonly")
        self.output_mode.current(0)
        self.output_mode.grid(row=4, column=1, sticky="ew", pady=(5, 0))

        ttk.Label(frame, text="Extra Instructions (optional)").grid(row=5, column=0, columnspan=2, sticky="w", pady=(10, 0))
        self.extra = tk.Text(frame, width=58, height=3)
        self.extra.grid(row=6, column=0, columnspan=2, sticky="ew")

        ttk.Label(frame, text="Prompt A / Main Source").grid(row=7, column=0, columnspan=2, sticky="w", pady=(10, 0))
        self.prompt_a = tk.Text(frame, width=58, height=7)
        self.prompt_a.grid(row=8, column=0, columnspan=2, sticky="ew")

        self.add_b_button = ttk.Button(frame, text="+ Add Prompt B", command=self.show_prompt_b)
        self.add_b_button.grid(row=9, column=0, sticky="ew", pady=(8, 0))
        self.prompt_b_label = ttk.Label(frame, text="Prompt B / Optional Second Source")
        self.prompt_b = tk.Text(frame, width=58, height=6)

        ttk.Button(frame, text="Build and Copy", command=self.build_and_copy).grid(row=12, column=0, sticky="ew", pady=(10, 0), padx=(0, 4))
        ttk.Button(frame, text="Close", command=self.window.destroy).grid(row=12, column=1, sticky="ew", pady=(10, 0), padx=(4, 0))
        self.keep_open = tk.BooleanVar(value=False)
        ttk.Checkbutton(frame, text="Keep Prompt Forge open after build", variable=self.keep_open).grid(row=13, column=0, columnspan=2, sticky="w", pady=(8, 0))
        ttk.Label(frame, textvariable=self.status_var).grid(row=14, column=0, columnspan=2, sticky="ew", pady=(8, 0))

    def show_prompt_b(self) -> None:
        if self.prompt_b_visible:
            return
        self.prompt_b_visible = True
        self.add_b_button.grid_remove()
        self.prompt_b_label.grid(row=9, column=0, columnspan=2, sticky="w", pady=(10, 0))
        self.prompt_b.grid(row=10, column=0, columnspan=2, sticky="ew")

    def transform_changed(self) -> None:
        if self.transform.get() == "Merge / Combine":
            self.show_prompt_b()

    def copy_prompt_coach(self) -> None:
        self.clipboard.copy(PROMPT_COACH_TEXT)
        self.status_var.set("Prompt Coach copied to clipboard.")

    def build_and_copy(self) -> None:
        transformation = self.transform.get() or "Merge / Combine"
        extra = self.extra.get("1.0", "end").strip()
        prompt_a = self.prompt_a.get("1.0", "end").strip()
        prompt_b = self.prompt_b.get("1.0", "end").strip() if self.prompt_b_visible else ""
        if not prompt_a:
            self.status_var.set("Prompt A is required for Build and Copy.")
            return
        output = [
            "Task:",
            "Create a finished reusable prompt from the source material below.",
            "",
            "Selected transformation:",
            transformation,
            "",
            "Extra instructions:",
            extra,
            "",
            "Prompt A / Main Source:",
            "---",
            prompt_a,
            "---",
            "",
        ]
        if prompt_b:
            output.extend(["Prompt B / Optional Second Source:", "---", prompt_b, "---", ""])
        output.extend(
            [
                "Output requirements:",
                "- Produce one complete prompt, not commentary about the prompt.",
                "- Preserve useful constraints from the source material.",
                "- Remove duplication and conflicting wording.",
                "- Resolve conflicts explicitly when Prompt A and Prompt B disagree.",
                "- Keep the final prompt ready to paste into an AI session.",
                "- Do not include placeholder text.",
            ]
        )
        self.clipboard.copy("\n".join(output))
        self.status_var.set("Built and copied to clipboard.")
        if not self.keep_open.get():
            self.window.destroy()


def write_pid_file(pid_file: Path, spec_path: Path) -> None:
    pid_file.parent.mkdir(parents=True, exist_ok=True)
    pid_file.write_text(json.dumps({"pid": os.getpid(), "spec_path": str(spec_path)}) + "\n", encoding="utf-8")


def remove_pid_file(pid_file: Path) -> None:
    try:
        pid_file.unlink()
    except FileNotFoundError:
        pass


def run_gui(spec: BoardSpec, clipboard_name: str = "auto", gui_backend: str = "auto") -> None:
    settings = SettingsStore(spec.repo_root / spec.settings_rel, spec.data.get("settings", {}))
    tk_ok, tk_error = tkinter_available()
    qt_ok, qt_error = pyqt6_available()
    if gui_backend == "tk" or (gui_backend == "auto" and tk_ok):
        if not tk_ok:
            raise RuntimeError(f"tkinter GUI backend requested but tkinter could not be imported: {tk_error}")
        gui = BoardGui(spec, settings, clipboard_name=clipboard_name)
        gui.run()
        return
    if gui_backend == "qt" or (gui_backend == "auto" and qt_ok):
        if not qt_ok:
            raise RuntimeError(f"PyQt6 GUI backend requested but PyQt6 could not be imported: {qt_error}")
        gui = QtBoardGui(spec, settings, clipboard_name=clipboard_name)
        gui.run()
        return
    if gui_backend in {"auto", "web"}:
        gui = WebBoardApp(spec, settings, clipboard_name=clipboard_name)
        gui.run()
        return
    raise ValueError(f"Unsupported GUI backend: {gui_backend}")


def test_load_prompts(spec: BoardSpec) -> int:
    errors = spec.validate_prompt_files()
    if errors:
        print("Prompt validation failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print("## Flat prompt-library validation")
    print(f"Product: {spec.product_name}")
    print(f"Profiles: {len(spec.profiles)}")
    print(f"Boards: {len(spec.boards)}")
    print(f"Prompt buttons per board: {spec.prompts_per_board}")
    print(f"Prompt entries: {len(spec.prompts)}")
    print("All mapped Markdown files exist and are non-empty.")
    return 0


def test_gui_smoke(spec: BoardSpec) -> int:
    clipboard = MemoryClipboard()
    model = RuntimeModel(spec, clipboard)
    profile = spec.profiles[0]
    board = spec.boards[0]
    prompt = spec.prompt(0, 0, 1)
    body = model.copy_prompt_slot(1)
    if clipboard.paste() != body:
        print("ERROR: clipboard did not receive prompt body", file=sys.stderr)
        return 1
    print("## Direct GUI smoke model path")
    print(f"Title: {spec.product_name}")
    print(f"Active profile: {profile['name']}")
    print(f"Active board: {board['name']}")
    print(f"Prompt buttons visible from spec: {spec.prompts_per_board}")
    print(f"Clicked button: 1 {prompt.label}")
    print("Clipboard: memory backend received the Markdown body.")
    return 0


def print_diagnostics(spec: BoardSpec) -> int:
    diagnostics = collect_diagnostics(spec)
    print("## Linux Hotkey Diagnostics")
    for key, value in diagnostics.items():
        print(f"{key}: {value}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run a generic Linux prompt/hotkey board from a compiled board spec.")
    parser.add_argument("--repo-root", default=".", help="Repo root. Default: current directory.")
    parser.add_argument("--spec", default=DEFAULT_SPEC, help="board_spec.json path, relative to repo root unless absolute.")
    parser.add_argument("--open-board", action="store_true", help="Open the GUI board directly without relying on global hotkeys.")
    parser.add_argument("--run-background", action="store_true", help="Start this board runtime and keep it alive. Opens the board directly in this first slice.")
    parser.add_argument("--pid-file", default="", help="PID file used by launchers/linux/stop_hotkey_board.sh.")
    parser.add_argument("--clipboard", choices=["auto", "tk", "external", "memory"], default="auto", help="Clipboard backend.")
    parser.add_argument("--gui-backend", choices=["auto", "tk", "qt", "web"], default="auto", help="GUI backend. auto uses tkinter when available, then PyQt6 when available, then the local browser fallback.")
    parser.add_argument("--test-load-prompts", action="store_true", help="Validate mapped prompt files.")
    parser.add_argument("--test-gui-smoke", action="store_true", help="Exercise direct board model path and memory clipboard without opening a GUI.")
    parser.add_argument("--diagnostics", action="store_true", help="Report Linux session/global-hotkey diagnostics.")
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()
    try:
        spec = BoardSpec.load(repo_root, args.spec)
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: could not load board spec: {exc}", file=sys.stderr)
        return 1

    if args.test_load_prompts:
        return test_load_prompts(spec)
    if args.test_gui_smoke:
        return test_gui_smoke(spec)
    if args.diagnostics:
        return print_diagnostics(spec)
    if args.open_board or args.run_background:
        pid_file = Path(args.pid_file).expanduser() if args.pid_file else None
        if pid_file is not None:
            write_pid_file(pid_file, spec.spec_path)
        try:
            if args.run_background:
                print("## Linux Hotkey Board Runtime")
                print(f"Product: {spec.product_name}")
                print("Global hotkey support is experimental and session-dependent.")
                print("Opening the board directly for this first generic Linux slice.")
                print_diagnostics(spec)
            run_gui(spec, clipboard_name=args.clipboard, gui_backend=args.gui_backend)
            return 0
        finally:
            if pid_file is not None:
                remove_pid_file(pid_file)

    parser.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
