#!/usr/bin/env python3
"""
Export eMachination CAD Patent Prompt-Rig prompt Markdown files to Espanso match YAML.

Input:
  prompts/index.ini

Output:
  Espanso YAML containing one trigger per prompt index entry.
"""

from __future__ import annotations

import argparse
import configparser
import re
import sys
from pathlib import Path


PROFILE_ABBR = {
    "rough_in_part_development": "ri",
    "mechanical_drawing_cleanup": "md",
    "cad_application_assist": "cad",
    "patent_drawing_standards": "pds",
    "patent_flowcharts_system_diagrams": "pfs",
    "figure_packet_release_review": "fp",
}

BOARD_ABBR = {
    "primary": "p",
    "secondary": "s",
    "tertiary": "t",
}


def sanitize_token(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = value.strip("-")
    return value or "x"


def yaml_double_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def yaml_block(value: str, indent: str = "      ") -> str:
    value = value.rstrip("\n")
    if not value:
        return f"{indent}\n"
    return "\n".join(f"{indent}{line}" for line in value.splitlines()) + "\n"


def make_trigger(section: str, prefix: str) -> str:
    parts = section.split(".")
    if len(parts) != 3:
        fallback = sanitize_token(section)
        return f":{prefix}-{fallback}"

    profile, board, slot = parts
    profile_part = PROFILE_ABBR.get(profile, sanitize_token(profile))
    board_part = BOARD_ABBR.get(board, sanitize_token(board))
    slot_part = slot.zfill(2) if slot.isdigit() else sanitize_token(slot)

    return f":{prefix}-{profile_part}-{board_part}{slot_part}"


def load_index(index_path: Path) -> configparser.ConfigParser:
    parser = configparser.ConfigParser(interpolation=None)
    parser.optionxform = str
    read_files = parser.read(index_path, encoding="utf-8")
    if not read_files:
        raise FileNotFoundError(f"Could not read index file: {index_path}")
    return parser


def export_prompts(repo_root: Path, output_path: Path, report_path: Path, trigger_prefix: str) -> int:
    index_path = repo_root / "prompts" / "index.ini"
    parser = load_index(index_path)

    matches: list[dict[str, str]] = []
    errors: list[str] = []

    for section in parser.sections():
        label = parser.get(section, "label", fallback="").strip()
        rel_path = parser.get(section, "path", fallback="").strip()

        if not label:
            errors.append(f"{section}: missing label")
            continue

        if not rel_path:
            errors.append(f"{section}: missing path")
            continue

        prompt_path = repo_root / rel_path
        if not prompt_path.exists():
            errors.append(f"{section}: missing prompt file: {prompt_path}")
            continue

        prompt_text = prompt_path.read_text(encoding="utf-8", errors="replace").rstrip()
        if not prompt_text:
            errors.append(f"{section}: empty prompt file: {prompt_path}")
            continue

        matches.append(
            {
                "section": section,
                "label": label,
                "path": rel_path,
                "trigger": make_trigger(section, trigger_prefix),
                "text": prompt_text,
            }
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8", newline="\n") as out:
        out.write("# Generated by tools/export_prompts_to_espanso.py\n")
        out.write(f"# Source index: {index_path}\n")
        out.write("# Review the report before installing into Espanso.\n")
        out.write("matches:\n")

        for item in matches:
            out.write(f"  - trigger: {yaml_double_quote(item['trigger'])}\n")
            out.write("    replace: |\n")
            out.write(yaml_block(item["text"]))
            out.write(f"    label: {yaml_double_quote(item['label'] + ' [' + item['section'] + ']')}\n")

        if not matches:
            out.write("  # No prompt matches were exported.\n")

    with report_path.open("w", encoding="utf-8", newline="\n") as report:
        report.write("# VeydraNet Prompt Board Espanso Export Report\n\n")
        report.write(f"Repo root: `{repo_root}`\n\n")
        report.write(f"Index file: `{index_path}`\n\n")
        report.write(f"Output YAML: `{output_path}`\n\n")
        report.write(f"Exported matches: **{len(matches)}**\n\n")

        if errors:
            report.write("## Errors\n\n")
            for error in errors:
                report.write(f"- {error}\n")
            report.write("\n")

        report.write("## Trigger map\n\n")
        for item in matches:
            report.write(
                f"- `{item['trigger']}` -> `{item['section']}` / "
                f"{item['label']} / `{item['path']}`\n"
            )

    if errors:
        print(f"Export completed with {len(errors)} error(s).")
        print(f"Generated YAML: {output_path}")
        print(f"Generated report: {report_path}")
        return 1

    print(f"Generated YAML: {output_path}")
    print(f"Generated report: {report_path}")
    print(f"Exported matches: {len(matches)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Repo root containing prompts/index.ini",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output Espanso YAML file path",
    )
    parser.add_argument(
        "--report",
        required=True,
        help="Output Markdown report file path",
    )
    parser.add_argument(
        "--trigger-prefix",
        default="vhb",
        help="Espanso trigger prefix without leading colon",
    )

    args = parser.parse_args()

    repo_root = Path(args.repo_root).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()
    report_path = Path(args.report).expanduser().resolve()
    trigger_prefix = sanitize_token(args.trigger_prefix)

    return export_prompts(repo_root, output_path, report_path, trigger_prefix)


if __name__ == "__main__":
    sys.exit(main())
